<?php

namespace Database\Seeders\Share;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UpazilaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $timestamp = Carbon::now()->toDateTimeString();
        $upazilas = array(
            array('id' => '1','district_id' => '1','name' => 'Debidwar','bn_name' => 'দেবিদ্বার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '2','district_id' => '1','name' => 'Barura','bn_name' => 'বরুড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '3','district_id' => '1','name' => 'Brahmanpara','bn_name' => 'ব্রাহ্মণপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '4','district_id' => '1','name' => 'Chandina','bn_name' => 'চান্দিনা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '5','district_id' => '1','name' => 'Chauddagram','bn_name' => 'চৌদ্দগ্রাম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '6','district_id' => '1','name' => 'Daudkandi','bn_name' => 'দাউদকান্দি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '7','district_id' => '1','name' => 'Homna','bn_name' => 'হোমনা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '8','district_id' => '1','name' => 'Laksam','bn_name' => 'লাকসাম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '9','district_id' => '1','name' => 'Muradnagar','bn_name' => 'মুরাদনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '10','district_id' => '1','name' => 'Nangalkot','bn_name' => 'নাঙ্গলকোট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '11','district_id' => '1','name' => 'Comilla Sadar','bn_name' => 'কুমিল্লা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '12','district_id' => '1','name' => 'Meghna','bn_name' => 'মেঘনা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '13','district_id' => '1','name' => 'Monohargonj','bn_name' => 'মনোহরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '14','district_id' => '1','name' => 'Sadarsouth','bn_name' => 'সদর দক্ষিণ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '15','district_id' => '1','name' => 'Titas','bn_name' => 'তিতাস','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '16','district_id' => '1','name' => 'Burichang','bn_name' => 'বুড়িচং','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '17','district_id' => '1','name' => 'Lalmai','bn_name' => 'লালমাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '18','district_id' => '2','name' => 'Chhagalnaiya','bn_name' => 'ছাগলনাইয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '19','district_id' => '2','name' => 'Feni Sadar','bn_name' => 'ফেনী সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '20','district_id' => '2','name' => 'Sonagazi','bn_name' => 'সোনাগাজী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '21','district_id' => '2','name' => 'Fulgazi','bn_name' => 'ফুলগাজী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '22','district_id' => '2','name' => 'Parshuram','bn_name' => 'পরশুরাম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '23','district_id' => '2','name' => 'Daganbhuiyan','bn_name' => 'দাগনভূঞা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '24','district_id' => '3','name' => 'Brahmanbaria Sadar','bn_name' => 'ব্রাহ্মণবাড়িয়া সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '25','district_id' => '3','name' => 'Kasba','bn_name' => 'কসবা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '26','district_id' => '3','name' => 'Nasirnagar','bn_name' => 'নাসিরনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '27','district_id' => '3','name' => 'Sarail','bn_name' => 'সরাইল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '28','district_id' => '3','name' => 'Ashuganj','bn_name' => 'আশুগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '29','district_id' => '3','name' => 'Akhaura','bn_name' => 'আখাউড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '30','district_id' => '3','name' => 'Nabinagar','bn_name' => 'নবীনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '31','district_id' => '3','name' => 'Bancharampur','bn_name' => 'বাঞ্ছারামপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '32','district_id' => '3','name' => 'Bijoynagar','bn_name' => 'বিজয়নগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '33','district_id' => '4','name' => 'Rangamati Sadar','bn_name' => 'রাঙ্গামাটি সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '34','district_id' => '4','name' => 'Kaptai','bn_name' => 'কাপ্তাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '35','district_id' => '4','name' => 'Kawkhali','bn_name' => 'কাউখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '36','district_id' => '4','name' => 'Baghaichari','bn_name' => 'বাঘাইছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '37','district_id' => '4','name' => 'Barkal','bn_name' => 'বরকল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '38','district_id' => '4','name' => 'Langadu','bn_name' => 'লংগদু','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '39','district_id' => '4','name' => 'Rajasthali','bn_name' => 'রাজস্থলী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '40','district_id' => '4','name' => 'Belaichari','bn_name' => 'বিলাইছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '41','district_id' => '4','name' => 'Juraichari','bn_name' => 'জুরাছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '42','district_id' => '4','name' => 'Naniarchar','bn_name' => 'নানিয়ারচর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '43','district_id' => '5','name' => 'Noakhali Sadar','bn_name' => 'নোয়াখালী সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '44','district_id' => '5','name' => 'Companiganj','bn_name' => 'কোম্পানীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '45','district_id' => '5','name' => 'Begumganj','bn_name' => 'বেগমগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '46','district_id' => '5','name' => 'Hatia','bn_name' => 'হাতিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '47','district_id' => '5','name' => 'Subarnachar','bn_name' => 'সুবর্ণচর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '48','district_id' => '5','name' => 'Kabirhat','bn_name' => 'কবিরহাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '49','district_id' => '5','name' => 'Senbug','bn_name' => 'সেনবাগ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '50','district_id' => '5','name' => 'Chatkhil','bn_name' => 'চাটখিল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '51','district_id' => '5','name' => 'Sonaimori','bn_name' => 'সোনাইমুড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '52','district_id' => '6','name' => 'Haimchar','bn_name' => 'হাইমচর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '53','district_id' => '6','name' => 'Kachua','bn_name' => 'কচুয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '54','district_id' => '6','name' => 'Shahrasti','bn_name' => 'শাহরাস্তি	','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '55','district_id' => '6','name' => 'Chandpur Sadar','bn_name' => 'চাঁদপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '56','district_id' => '6','name' => 'Matlab South','bn_name' => 'মতলব দক্ষিণ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '57','district_id' => '6','name' => 'Hajiganj','bn_name' => 'হাজীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '58','district_id' => '6','name' => 'Matlab North','bn_name' => 'মতলব উত্তর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '59','district_id' => '6','name' => 'Faridgonj','bn_name' => 'ফরিদগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '60','district_id' => '7','name' => 'Lakshmipur Sadar','bn_name' => 'লক্ষ্মীপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '61','district_id' => '7','name' => 'Kamalnagar','bn_name' => 'কমলনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '62','district_id' => '7','name' => 'Raipur','bn_name' => 'রায়পুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '63','district_id' => '7','name' => 'Ramgati','bn_name' => 'রামগতি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '64','district_id' => '7','name' => 'Ramganj','bn_name' => 'রামগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '65','district_id' => '8','name' => 'Rangunia','bn_name' => 'রাঙ্গুনিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '66','district_id' => '8','name' => 'Sitakunda','bn_name' => 'সীতাকুন্ড','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '67','district_id' => '8','name' => 'Mirsharai','bn_name' => 'মীরসরাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '68','district_id' => '8','name' => 'Patiya','bn_name' => 'পটিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '69','district_id' => '8','name' => 'Sandwip','bn_name' => 'সন্দ্বীপ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '70','district_id' => '8','name' => 'Banshkhali','bn_name' => 'বাঁশখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '71','district_id' => '8','name' => 'Boalkhali','bn_name' => 'বোয়ালখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '72','district_id' => '8','name' => 'Anwara','bn_name' => 'আনোয়ারা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '73','district_id' => '8','name' => 'Chandanaish','bn_name' => 'চন্দনাইশ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '74','district_id' => '8','name' => 'Satkania','bn_name' => 'সাতকানিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '75','district_id' => '8','name' => 'Lohagara','bn_name' => 'লোহাগাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '76','district_id' => '8','name' => 'Hathazari','bn_name' => 'হাটহাজারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '77','district_id' => '8','name' => 'Fatikchhari','bn_name' => 'ফটিকছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '78','district_id' => '8','name' => 'Raozan','bn_name' => 'রাউজান','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '79','district_id' => '8','name' => 'Karnafuli','bn_name' => 'কর্ণফুলী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '80','district_id' => '9','name' => 'Coxsbazar Sadar','bn_name' => 'কক্সবাজার সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '81','district_id' => '9','name' => 'Chakaria','bn_name' => 'চকরিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '82','district_id' => '9','name' => 'Kutubdia','bn_name' => 'কুতুবদিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '83','district_id' => '9','name' => 'Ukhiya','bn_name' => 'উখিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '84','district_id' => '9','name' => 'Moheshkhali','bn_name' => 'মহেশখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '85','district_id' => '9','name' => 'Pekua','bn_name' => 'পেকুয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '86','district_id' => '9','name' => 'Ramu','bn_name' => 'রামু','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '87','district_id' => '9','name' => 'Teknaf','bn_name' => 'টেকনাফ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '88','district_id' => '10','name' => 'Khagrachhari Sadar','bn_name' => 'খাগড়াছড়ি সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '89','district_id' => '10','name' => 'Dighinala','bn_name' => 'দিঘীনালা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '90','district_id' => '10','name' => 'Panchari','bn_name' => 'পানছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '91','district_id' => '10','name' => 'Laxmichhari','bn_name' => 'লক্ষীছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '92','district_id' => '10','name' => 'Mohalchari','bn_name' => 'মহালছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '93','district_id' => '10','name' => 'Manikchari','bn_name' => 'মানিকছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '94','district_id' => '10','name' => 'Ramgarh','bn_name' => 'রামগড়','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '95','district_id' => '10','name' => 'Matiranga','bn_name' => 'মাটিরাঙ্গা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '96','district_id' => '10','name' => 'Guimara','bn_name' => 'গুইমারা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '97','district_id' => '11','name' => 'Bandarban Sadar','bn_name' => 'বান্দরবান সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '98','district_id' => '11','name' => 'Alikadam','bn_name' => 'আলীকদম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '99','district_id' => '11','name' => 'Naikhongchhari','bn_name' => 'নাইক্ষ্যংছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '100','district_id' => '11','name' => 'Rowangchhari','bn_name' => 'রোয়াংছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '101','district_id' => '11','name' => 'Lama','bn_name' => 'লামা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '102','district_id' => '11','name' => 'Ruma','bn_name' => 'রুমা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '103','district_id' => '11','name' => 'Thanchi','bn_name' => 'থানচি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '104','district_id' => '12','name' => 'Belkuchi','bn_name' => 'বেলকুচি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '105','district_id' => '12','name' => 'Chauhali','bn_name' => 'চৌহালি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '106','district_id' => '12','name' => 'Kamarkhand','bn_name' => 'কামারখন্দ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '107','district_id' => '12','name' => 'Kazipur','bn_name' => 'কাজীপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '108','district_id' => '12','name' => 'Raigonj','bn_name' => 'রায়গঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '109','district_id' => '12','name' => 'Shahjadpur','bn_name' => 'শাহজাদপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '110','district_id' => '12','name' => 'Sirajganj Sadar','bn_name' => 'সিরাজগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '111','district_id' => '12','name' => 'Tarash','bn_name' => 'তাড়াশ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '112','district_id' => '12','name' => 'Ullapara','bn_name' => 'উল্লাপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '113','district_id' => '13','name' => 'Sujanagar','bn_name' => 'সুজানগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '114','district_id' => '13','name' => 'Ishurdi','bn_name' => 'ঈশ্বরদী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '115','district_id' => '13','name' => 'Bhangura','bn_name' => 'ভাঙ্গুড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '116','district_id' => '13','name' => 'Pabna Sadar','bn_name' => 'পাবনা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '117','district_id' => '13','name' => 'Bera','bn_name' => 'বেড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '118','district_id' => '13','name' => 'Atghoria','bn_name' => 'আটঘরিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '119','district_id' => '13','name' => 'Chatmohar','bn_name' => 'চাটমোহর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '120','district_id' => '13','name' => 'Santhia','bn_name' => 'সাঁথিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '121','district_id' => '13','name' => 'Faridpur','bn_name' => 'ফরিদপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '122','district_id' => '14','name' => 'Kahaloo','bn_name' => 'কাহালু','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '123','district_id' => '14','name' => 'Bogra Sadar','bn_name' => 'বগুড়া সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '124','district_id' => '14','name' => 'Shariakandi','bn_name' => 'সারিয়াকান্দি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '125','district_id' => '14','name' => 'Shajahanpur','bn_name' => 'শাজাহানপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '126','district_id' => '14','name' => 'Dupchanchia','bn_name' => 'দুপচাচিঁয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '127','district_id' => '14','name' => 'Adamdighi','bn_name' => 'আদমদিঘি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '128','district_id' => '14','name' => 'Nondigram','bn_name' => 'নন্দিগ্রাম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '129','district_id' => '14','name' => 'Sonatala','bn_name' => 'সোনাতলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '130','district_id' => '14','name' => 'Dhunot','bn_name' => 'ধুনট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '131','district_id' => '14','name' => 'Gabtali','bn_name' => 'গাবতলী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '132','district_id' => '14','name' => 'Sherpur','bn_name' => 'শেরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '133','district_id' => '14','name' => 'Shibganj','bn_name' => 'শিবগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '134','district_id' => '15','name' => 'Paba','bn_name' => 'পবা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '135','district_id' => '15','name' => 'Durgapur','bn_name' => 'দুর্গাপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '136','district_id' => '15','name' => 'Mohonpur','bn_name' => 'মোহনপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '137','district_id' => '15','name' => 'Charghat','bn_name' => 'চারঘাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '138','district_id' => '15','name' => 'Puthia','bn_name' => 'পুঠিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '139','district_id' => '15','name' => 'Bagha','bn_name' => 'বাঘা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '140','district_id' => '15','name' => 'Godagari','bn_name' => 'গোদাগাড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '141','district_id' => '15','name' => 'Tanore','bn_name' => 'তানোর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '142','district_id' => '15','name' => 'Bagmara','bn_name' => 'বাগমারা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '143','district_id' => '16','name' => 'Natore Sadar','bn_name' => 'নাটোর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '144','district_id' => '16','name' => 'Singra','bn_name' => 'সিংড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '145','district_id' => '16','name' => 'Baraigram','bn_name' => 'বড়াইগ্রাম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '146','district_id' => '16','name' => 'Bagatipara','bn_name' => 'বাগাতিপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '147','district_id' => '16','name' => 'Lalpur','bn_name' => 'লালপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '148','district_id' => '16','name' => 'Gurudaspur','bn_name' => 'গুরুদাসপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '149','district_id' => '16','name' => 'Naldanga','bn_name' => 'নলডাঙ্গা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '150','district_id' => '17','name' => 'Akkelpur','bn_name' => 'আক্কেলপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '151','district_id' => '17','name' => 'Kalai','bn_name' => 'কালাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '152','district_id' => '17','name' => 'Khetlal','bn_name' => 'ক্ষেতলাল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '153','district_id' => '17','name' => 'Panchbibi','bn_name' => 'পাঁচবিবি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '154','district_id' => '17','name' => 'Joypurhat Sadar','bn_name' => 'জয়পুরহাট সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '155','district_id' => '18','name' => 'Chapainawabganj Sadar','bn_name' => 'চাঁপাইনবাবগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '156','district_id' => '18','name' => 'Gomostapur','bn_name' => 'গোমস্তাপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '157','district_id' => '18','name' => 'Nachol','bn_name' => 'নাচোল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '158','district_id' => '18','name' => 'Bholahat','bn_name' => 'ভোলাহাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '159','district_id' => '18','name' => 'Shibganj','bn_name' => 'শিবগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '160','district_id' => '19','name' => 'Mohadevpur','bn_name' => 'মহাদেবপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '161','district_id' => '19','name' => 'Badalgachi','bn_name' => 'বদলগাছী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '162','district_id' => '19','name' => 'Patnitala','bn_name' => 'পত্নিতলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '163','district_id' => '19','name' => 'Dhamoirhat','bn_name' => 'ধামইরহাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '164','district_id' => '19','name' => 'Niamatpur','bn_name' => 'নিয়ামতপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '165','district_id' => '19','name' => 'Manda','bn_name' => 'মান্দা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '166','district_id' => '19','name' => 'Atrai','bn_name' => 'আত্রাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '167','district_id' => '19','name' => 'Raninagar','bn_name' => 'রাণীনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '168','district_id' => '19','name' => 'Naogaon Sadar','bn_name' => 'নওগাঁ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '169','district_id' => '19','name' => 'Porsha','bn_name' => 'পোরশা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '170','district_id' => '19','name' => 'Sapahar','bn_name' => 'সাপাহার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '171','district_id' => '20','name' => 'Manirampur','bn_name' => 'মণিরামপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '172','district_id' => '20','name' => 'Abhaynagar','bn_name' => 'অভয়নগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '173','district_id' => '20','name' => 'Bagherpara','bn_name' => 'বাঘারপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '174','district_id' => '20','name' => 'Chougachha','bn_name' => 'চৌগাছা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '175','district_id' => '20','name' => 'Jhikargacha','bn_name' => 'ঝিকরগাছা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '176','district_id' => '20','name' => 'Keshabpur','bn_name' => 'কেশবপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '177','district_id' => '20','name' => 'Jessore Sadar','bn_name' => 'যশোর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '178','district_id' => '20','name' => 'Sharsha','bn_name' => 'শার্শা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '179','district_id' => '21','name' => 'Assasuni','bn_name' => 'আশাশুনি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '180','district_id' => '21','name' => 'Debhata','bn_name' => 'দেবহাটা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '181','district_id' => '21','name' => 'Kalaroa','bn_name' => 'কলারোয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '182','district_id' => '21','name' => 'Satkhira Sadar','bn_name' => 'সাতক্ষীরা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '183','district_id' => '21','name' => 'Shyamnagar','bn_name' => 'শ্যামনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '184','district_id' => '21','name' => 'Tala','bn_name' => 'তালা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '185','district_id' => '21','name' => 'Kaliganj','bn_name' => 'কালিগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '186','district_id' => '22','name' => 'Mujibnagar','bn_name' => 'মুজিবনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '187','district_id' => '22','name' => 'Meherpur Sadar','bn_name' => 'মেহেরপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '188','district_id' => '22','name' => 'Gangni','bn_name' => 'গাংনী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '189','district_id' => '23','name' => 'Narail Sadar','bn_name' => 'নড়াইল সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '190','district_id' => '23','name' => 'Lohagara','bn_name' => 'লোহাগড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '191','district_id' => '23','name' => 'Kalia','bn_name' => 'কালিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '192','district_id' => '24','name' => 'Chuadanga Sadar','bn_name' => 'চুয়াডাঙ্গা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '193','district_id' => '24','name' => 'Alamdanga','bn_name' => 'আলমডাঙ্গা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '194','district_id' => '24','name' => 'Damurhuda','bn_name' => 'দামুড়হুদা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '195','district_id' => '24','name' => 'Jibannagar','bn_name' => 'জীবননগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '196','district_id' => '25','name' => 'Kushtia Sadar','bn_name' => 'কুষ্টিয়া সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '197','district_id' => '25','name' => 'Kumarkhali','bn_name' => 'কুমারখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '198','district_id' => '25','name' => 'Khoksa','bn_name' => 'খোকসা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '199','district_id' => '25','name' => 'Mirpur','bn_name' => 'মিরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '200','district_id' => '25','name' => 'Daulatpur','bn_name' => 'দৌলতপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '201','district_id' => '25','name' => 'Bheramara','bn_name' => 'ভেড়ামারা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '202','district_id' => '26','name' => 'Shalikha','bn_name' => 'শালিখা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '203','district_id' => '26','name' => 'Sreepur','bn_name' => 'শ্রীপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '204','district_id' => '26','name' => 'Magura Sadar','bn_name' => 'মাগুরা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '205','district_id' => '26','name' => 'Mohammadpur','bn_name' => 'মহম্মদপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '206','district_id' => '27','name' => 'Paikgasa','bn_name' => 'পাইকগাছা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '207','district_id' => '27','name' => 'Fultola','bn_name' => 'ফুলতলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '208','district_id' => '27','name' => 'Digholia','bn_name' => 'দিঘলিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '209','district_id' => '27','name' => 'Rupsha','bn_name' => 'রূপসা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '210','district_id' => '27','name' => 'Terokhada','bn_name' => 'তেরখাদা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '211','district_id' => '27','name' => 'Dumuria','bn_name' => 'ডুমুরিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '212','district_id' => '27','name' => 'Botiaghata','bn_name' => 'বটিয়াঘাটা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '213','district_id' => '27','name' => 'Dakop','bn_name' => 'দাকোপ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '214','district_id' => '27','name' => 'Koyra','bn_name' => 'কয়রা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '215','district_id' => '28','name' => 'Fakirhat','bn_name' => 'ফকিরহাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '216','district_id' => '28','name' => 'Bagerhat Sadar','bn_name' => 'বাগেরহাট সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '217','district_id' => '28','name' => 'Mollahat','bn_name' => 'মোল্লাহাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '218','district_id' => '28','name' => 'Sarankhola','bn_name' => 'শরণখোলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '219','district_id' => '28','name' => 'Rampal','bn_name' => 'রামপাল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '220','district_id' => '28','name' => 'Morrelganj','bn_name' => 'মোড়েলগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '221','district_id' => '28','name' => 'Kachua','bn_name' => 'কচুয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '222','district_id' => '28','name' => 'Mongla','bn_name' => 'মোংলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '223','district_id' => '28','name' => 'Chitalmari','bn_name' => 'চিতলমারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '224','district_id' => '29','name' => 'Jhenaidah Sadar','bn_name' => 'ঝিনাইদহ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '225','district_id' => '29','name' => 'Shailkupa','bn_name' => 'শৈলকুপা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '226','district_id' => '29','name' => 'Harinakundu','bn_name' => 'হরিণাকুন্ডু','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '227','district_id' => '29','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '228','district_id' => '29','name' => 'Kotchandpur','bn_name' => 'কোটচাঁদপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '229','district_id' => '29','name' => 'Moheshpur','bn_name' => 'মহেশপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '230','district_id' => '30','name' => 'Jhalakathi Sadar','bn_name' => 'ঝালকাঠি সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '231','district_id' => '30','name' => 'Kathalia','bn_name' => 'কাঠালিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '232','district_id' => '30','name' => 'Nalchity','bn_name' => 'নলছিটি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '233','district_id' => '30','name' => 'Rajapur','bn_name' => 'রাজাপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '234','district_id' => '31','name' => 'Bauphal','bn_name' => 'বাউফল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '235','district_id' => '31','name' => 'Patuakhali Sadar','bn_name' => 'পটুয়াখালী সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '236','district_id' => '31','name' => 'Dumki','bn_name' => 'দুমকি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '237','district_id' => '31','name' => 'Dashmina','bn_name' => 'দশমিনা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '238','district_id' => '31','name' => 'Kalapara','bn_name' => 'কলাপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '239','district_id' => '31','name' => 'Mirzaganj','bn_name' => 'মির্জাগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '240','district_id' => '31','name' => 'Galachipa','bn_name' => 'গলাচিপা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '241','district_id' => '31','name' => 'Rangabali','bn_name' => 'রাঙ্গাবালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '242','district_id' => '32','name' => 'Pirojpur Sadar','bn_name' => 'পিরোজপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '243','district_id' => '32','name' => 'Nazirpur','bn_name' => 'নাজিরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '244','district_id' => '32','name' => 'Kawkhali','bn_name' => 'কাউখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '245','district_id' => '32','name' => 'Zianagar','bn_name' => 'জিয়ানগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '246','district_id' => '32','name' => 'Bhandaria','bn_name' => 'ভান্ডারিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '247','district_id' => '32','name' => 'Mathbaria','bn_name' => 'মঠবাড়ীয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '248','district_id' => '32','name' => 'Nesarabad','bn_name' => 'নেছারাবাদ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '249','district_id' => '33','name' => 'Barisal Sadar','bn_name' => 'বরিশাল সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '250','district_id' => '33','name' => 'Bakerganj','bn_name' => 'বাকেরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '251','district_id' => '33','name' => 'Babuganj','bn_name' => 'বাবুগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '252','district_id' => '33','name' => 'Wazirpur','bn_name' => 'উজিরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '253','district_id' => '33','name' => 'Banaripara','bn_name' => 'বানারীপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '254','district_id' => '33','name' => 'Gournadi','bn_name' => 'গৌরনদী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '255','district_id' => '33','name' => 'Agailjhara','bn_name' => 'আগৈলঝাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '256','district_id' => '33','name' => 'Mehendiganj','bn_name' => 'মেহেন্দিগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '257','district_id' => '33','name' => 'Muladi','bn_name' => 'মুলাদী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '258','district_id' => '33','name' => 'Hizla','bn_name' => 'হিজলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '259','district_id' => '34','name' => 'Bhola Sadar','bn_name' => 'ভোলা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '260','district_id' => '34','name' => 'Borhan Sddin','bn_name' => 'বোরহান উদ্দিন','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '261','district_id' => '34','name' => 'Charfesson','bn_name' => 'চরফ্যাশন','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '262','district_id' => '34','name' => 'Doulatkhan','bn_name' => 'দৌলতখান','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '263','district_id' => '34','name' => 'Monpura','bn_name' => 'মনপুরা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '264','district_id' => '34','name' => 'Tazumuddin','bn_name' => 'তজুমদ্দিন','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '265','district_id' => '34','name' => 'Lalmohan','bn_name' => 'লালমোহন','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '266','district_id' => '35','name' => 'Amtali','bn_name' => 'আমতলী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '267','district_id' => '35','name' => 'Barguna Sadar','bn_name' => 'বরগুনা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '268','district_id' => '35','name' => 'Betagi','bn_name' => 'বেতাগী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '269','district_id' => '35','name' => 'Bamna','bn_name' => 'বামনা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '270','district_id' => '35','name' => 'Pathorghata','bn_name' => 'পাথরঘাটা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '271','district_id' => '35','name' => 'Taltali','bn_name' => 'তালতলি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '272','district_id' => '36','name' => 'Balaganj','bn_name' => 'বালাগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '273','district_id' => '36','name' => 'Beanibazar','bn_name' => 'বিয়ানীবাজার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '274','district_id' => '36','name' => 'Bishwanath','bn_name' => 'বিশ্বনাথ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '275','district_id' => '36','name' => 'Companiganj','bn_name' => 'কোম্পানীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '276','district_id' => '36','name' => 'Fenchuganj','bn_name' => 'ফেঞ্চুগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '277','district_id' => '36','name' => 'Golapganj','bn_name' => 'গোলাপগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '278','district_id' => '36','name' => 'Gowainghat','bn_name' => 'গোয়াইনঘাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '279','district_id' => '36','name' => 'Jaintiapur','bn_name' => 'জৈন্তাপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '280','district_id' => '36','name' => 'Kanaighat','bn_name' => 'কানাইঘাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '281','district_id' => '36','name' => 'Sylhet Sadar','bn_name' => 'সিলেট সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '282','district_id' => '36','name' => 'Zakiganj','bn_name' => 'জকিগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '283','district_id' => '36','name' => 'Dakshinsurma','bn_name' => 'দক্ষিণ সুরমা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '284','district_id' => '36','name' => 'Osmaninagar','bn_name' => 'ওসমানী নগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '285','district_id' => '37','name' => 'Barlekha','bn_name' => 'বড়লেখা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '286','district_id' => '37','name' => 'Kamolganj','bn_name' => 'কমলগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '287','district_id' => '37','name' => 'Kulaura','bn_name' => 'কুলাউড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '288','district_id' => '37','name' => 'Moulvibazar Sadar','bn_name' => 'মৌলভীবাজার সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '289','district_id' => '37','name' => 'Rajnagar','bn_name' => 'রাজনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '290','district_id' => '37','name' => 'Sreemangal','bn_name' => 'শ্রীমঙ্গল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '291','district_id' => '37','name' => 'Juri','bn_name' => 'জুড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '292','district_id' => '38','name' => 'Nabiganj','bn_name' => 'নবীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '293','district_id' => '38','name' => 'Bahubal','bn_name' => 'বাহুবল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '294','district_id' => '38','name' => 'Ajmiriganj','bn_name' => 'আজমিরীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '295','district_id' => '38','name' => 'Baniachong','bn_name' => 'বানিয়াচং','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '296','district_id' => '38','name' => 'Lakhai','bn_name' => 'লাখাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '297','district_id' => '38','name' => 'Chunarughat','bn_name' => 'চুনারুঘাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '298','district_id' => '38','name' => 'Habiganj Sadar','bn_name' => 'হবিগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '299','district_id' => '38','name' => 'Madhabpur','bn_name' => 'মাধবপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '300','district_id' => '39','name' => 'Sunamganj Sadar','bn_name' => 'সুনামগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '301','district_id' => '39','name' => 'South Sunamganj','bn_name' => 'দক্ষিণ সুনামগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '302','district_id' => '39','name' => 'Bishwambarpur','bn_name' => 'বিশ্বম্ভরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '303','district_id' => '39','name' => 'Chhatak','bn_name' => 'ছাতক','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '304','district_id' => '39','name' => 'Jagannathpur','bn_name' => 'জগন্নাথপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '305','district_id' => '39','name' => 'Dowarabazar','bn_name' => 'দোয়ারাবাজার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '306','district_id' => '39','name' => 'Tahirpur','bn_name' => 'তাহিরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '307','district_id' => '39','name' => 'Dharmapasha','bn_name' => 'ধর্মপাশা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '308','district_id' => '39','name' => 'Jamalganj','bn_name' => 'জামালগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '309','district_id' => '39','name' => 'Shalla','bn_name' => 'শাল্লা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '310','district_id' => '39','name' => 'Derai','bn_name' => 'দিরাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '311','district_id' => '40','name' => 'Belabo','bn_name' => 'বেলাবো','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '312','district_id' => '40','name' => 'Monohardi','bn_name' => 'মনোহরদী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '313','district_id' => '40','name' => 'Narsingdi Sadar','bn_name' => 'নরসিংদী সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '314','district_id' => '40','name' => 'Palash','bn_name' => 'পলাশ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '315','district_id' => '40','name' => 'Raipura','bn_name' => 'রায়পুরা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '316','district_id' => '40','name' => 'Shibpur','bn_name' => 'শিবপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '317','district_id' => '41','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '318','district_id' => '41','name' => 'Kaliakair','bn_name' => 'কালিয়াকৈর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '319','district_id' => '41','name' => 'Kapasia','bn_name' => 'কাপাসিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '320','district_id' => '41','name' => 'Gazipur Sadar','bn_name' => 'গাজীপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '321','district_id' => '41','name' => 'Sreepur','bn_name' => 'শ্রীপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '322','district_id' => '42','name' => 'Shariatpur Sadar','bn_name' => 'শরিয়তপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '323','district_id' => '42','name' => 'Naria','bn_name' => 'নড়িয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '324','district_id' => '42','name' => 'Zajira','bn_name' => 'জাজিরা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '325','district_id' => '42','name' => 'Gosairhat','bn_name' => 'গোসাইরহাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '326','district_id' => '42','name' => 'Bhedarganj','bn_name' => 'ভেদরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '327','district_id' => '42','name' => 'Damudya','bn_name' => 'ডামুড্যা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '328','district_id' => '43','name' => 'Araihazar','bn_name' => 'আড়াইহাজার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '329','district_id' => '43','name' => 'Bandar','bn_name' => 'বন্দর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '330','district_id' => '43','name' => 'Narayanganj Sadar','bn_name' => 'নারায়নগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '331','district_id' => '43','name' => 'Rupganj','bn_name' => 'রূপগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '332','district_id' => '43','name' => 'Sonargaon','bn_name' => 'সোনারগাঁ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '333','district_id' => '44','name' => 'Basail','bn_name' => 'বাসাইল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '334','district_id' => '44','name' => 'Bhuapur','bn_name' => 'ভুয়াপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '335','district_id' => '44','name' => 'Delduar','bn_name' => 'দেলদুয়ার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '336','district_id' => '44','name' => 'Ghatail','bn_name' => 'ঘাটাইল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '337','district_id' => '44','name' => 'Gopalpur','bn_name' => 'গোপালপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '338','district_id' => '44','name' => 'Madhupur','bn_name' => 'মধুপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '339','district_id' => '44','name' => 'Mirzapur','bn_name' => 'মির্জাপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '340','district_id' => '44','name' => 'Nagarpur','bn_name' => 'নাগরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '341','district_id' => '44','name' => 'Sakhipur','bn_name' => 'সখিপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '342','district_id' => '44','name' => 'Tangail Sadar','bn_name' => 'টাঙ্গাইল সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '343','district_id' => '44','name' => 'Kalihati','bn_name' => 'কালিহাতী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '344','district_id' => '44','name' => 'Dhanbari','bn_name' => 'ধনবাড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '345','district_id' => '45','name' => 'Itna','bn_name' => 'ইটনা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '346','district_id' => '45','name' => 'Katiadi','bn_name' => 'কটিয়াদী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '347','district_id' => '45','name' => 'Bhairab','bn_name' => 'ভৈরব','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '348','district_id' => '45','name' => 'Tarail','bn_name' => 'তাড়াইল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '349','district_id' => '45','name' => 'Hossainpur','bn_name' => 'হোসেনপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '350','district_id' => '45','name' => 'Pakundia','bn_name' => 'পাকুন্দিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '351','district_id' => '45','name' => 'Kuliarchar','bn_name' => 'কুলিয়ারচর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '352','district_id' => '45','name' => 'Kishoreganj Sadar','bn_name' => 'কিশোরগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '353','district_id' => '45','name' => 'Karimgonj','bn_name' => 'করিমগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '354','district_id' => '45','name' => 'Bajitpur','bn_name' => 'বাজিতপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '355','district_id' => '45','name' => 'Austagram','bn_name' => 'অষ্টগ্রাম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '356','district_id' => '45','name' => 'Mithamoin','bn_name' => 'মিঠামইন','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '357','district_id' => '45','name' => 'Nikli','bn_name' => 'নিকলী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '358','district_id' => '46','name' => 'Harirampur','bn_name' => 'হরিরামপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '359','district_id' => '46','name' => 'Saturia','bn_name' => 'সাটুরিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '360','district_id' => '46','name' => 'Manikganj Sadar','bn_name' => 'মানিকগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '361','district_id' => '46','name' => 'Gior','bn_name' => 'ঘিওর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '362','district_id' => '46','name' => 'Shibaloy','bn_name' => 'শিবালয়','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '363','district_id' => '46','name' => 'Doulatpur','bn_name' => 'দৌলতপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '364','district_id' => '46','name' => 'Singiar','bn_name' => 'সিংগাইর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '365','district_id' => '47','name' => 'Savar','bn_name' => 'সাভার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '366','district_id' => '47','name' => 'Dhamrai','bn_name' => 'ধামরাই','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '367','district_id' => '47','name' => 'Keraniganj','bn_name' => 'কেরাণীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '368','district_id' => '47','name' => 'Nawabganj','bn_name' => 'নবাবগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '369','district_id' => '47','name' => 'Dohar','bn_name' => 'দোহার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '370','district_id' => '48','name' => 'Munshiganj Sadar','bn_name' => 'মুন্সিগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '371','district_id' => '48','name' => 'Sreenagar','bn_name' => 'শ্রীনগর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '372','district_id' => '48','name' => 'Sirajdikhan','bn_name' => 'সিরাজদিখান','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '373','district_id' => '48','name' => 'Louhajanj','bn_name' => 'লৌহজং','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '374','district_id' => '48','name' => 'Gajaria','bn_name' => 'গজারিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '375','district_id' => '48','name' => 'Tongibari','bn_name' => 'টংগীবাড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '376','district_id' => '49','name' => 'Rajbari Sadar','bn_name' => 'রাজবাড়ী সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '377','district_id' => '49','name' => 'Goalanda','bn_name' => 'গোয়ালন্দ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '378','district_id' => '49','name' => 'Pangsa','bn_name' => 'পাংশা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '379','district_id' => '49','name' => 'Baliakandi','bn_name' => 'বালিয়াকান্দি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '380','district_id' => '49','name' => 'Kalukhali','bn_name' => 'কালুখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '381','district_id' => '50','name' => 'Madaripur Sadar','bn_name' => 'মাদারীপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '382','district_id' => '50','name' => 'Shibchar','bn_name' => 'শিবচর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '383','district_id' => '50','name' => 'Kalkini','bn_name' => 'কালকিনি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '384','district_id' => '50','name' => 'Rajoir','bn_name' => 'রাজৈর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '385','district_id' => '51','name' => 'Gopalganj Sadar','bn_name' => 'গোপালগঞ্জ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '386','district_id' => '51','name' => 'Kashiani','bn_name' => 'কাশিয়ানী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '387','district_id' => '51','name' => 'Tungipara','bn_name' => 'টুংগীপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '388','district_id' => '51','name' => 'Kotalipara','bn_name' => 'কোটালীপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '389','district_id' => '51','name' => 'Muksudpur','bn_name' => 'মুকসুদপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '390','district_id' => '52','name' => 'Faridpur Sadar','bn_name' => 'ফরিদপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '391','district_id' => '52','name' => 'Alfadanga','bn_name' => 'আলফাডাঙ্গা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '392','district_id' => '52','name' => 'Boalmari','bn_name' => 'বোয়ালমারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '393','district_id' => '52','name' => 'Sadarpur','bn_name' => 'সদরপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '394','district_id' => '52','name' => 'Nagarkanda','bn_name' => 'নগরকান্দা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '395','district_id' => '52','name' => 'Bhanga','bn_name' => 'ভাঙ্গা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '396','district_id' => '52','name' => 'Charbhadrasan','bn_name' => 'চরভদ্রাসন','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '397','district_id' => '52','name' => 'Madhukhali','bn_name' => 'মধুখালী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '398','district_id' => '52','name' => 'Saltha','bn_name' => 'সালথা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '399','district_id' => '53','name' => 'Panchagarh Sadar','bn_name' => 'পঞ্চগড় সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '400','district_id' => '53','name' => 'Debiganj','bn_name' => 'দেবীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '401','district_id' => '53','name' => 'Boda','bn_name' => 'বোদা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '402','district_id' => '53','name' => 'Atwari','bn_name' => 'আটোয়ারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '403','district_id' => '53','name' => 'Tetulia','bn_name' => 'তেতুলিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '404','district_id' => '54','name' => 'Nawabganj','bn_name' => 'নবাবগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '405','district_id' => '54','name' => 'Birganj','bn_name' => 'বীরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '406','district_id' => '54','name' => 'Ghoraghat','bn_name' => 'ঘোড়াঘাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '407','district_id' => '54','name' => 'Birampur','bn_name' => 'বিরামপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '408','district_id' => '54','name' => 'Parbatipur','bn_name' => 'পার্বতীপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '409','district_id' => '54','name' => 'Bochaganj','bn_name' => 'বোচাগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '410','district_id' => '54','name' => 'Kaharol','bn_name' => 'কাহারোল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '411','district_id' => '54','name' => 'Fulbari','bn_name' => 'ফুলবাড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '412','district_id' => '54','name' => 'Dinajpur Sadar','bn_name' => 'দিনাজপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '413','district_id' => '54','name' => 'Hakimpur','bn_name' => 'হাকিমপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '414','district_id' => '54','name' => 'Khansama','bn_name' => 'খানসামা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '415','district_id' => '54','name' => 'Birol','bn_name' => 'বিরল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '416','district_id' => '54','name' => 'Chirirbandar','bn_name' => 'চিরিরবন্দর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '417','district_id' => '55','name' => 'Lalmonirhat Sadar','bn_name' => 'লালমনিরহাট সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '418','district_id' => '55','name' => 'Kaliganj','bn_name' => 'কালীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '419','district_id' => '55','name' => 'Hatibandha','bn_name' => 'হাতীবান্ধা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '420','district_id' => '55','name' => 'Patgram','bn_name' => 'পাটগ্রাম','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '421','district_id' => '55','name' => 'Aditmari','bn_name' => 'আদিতমারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '422','district_id' => '56','name' => 'Syedpur','bn_name' => 'সৈয়দপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '423','district_id' => '56','name' => 'Domar','bn_name' => 'ডোমার','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '424','district_id' => '56','name' => 'Dimla','bn_name' => 'ডিমলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '425','district_id' => '56','name' => 'Jaldhaka','bn_name' => 'জলঢাকা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '426','district_id' => '56','name' => 'Kishorganj','bn_name' => 'কিশোরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '427','district_id' => '56','name' => 'Nilphamari Sadar','bn_name' => 'নীলফামারী সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '428','district_id' => '57','name' => 'Sadullapur','bn_name' => 'সাদুল্লাপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '429','district_id' => '57','name' => 'Gaibandha Sadar','bn_name' => 'গাইবান্ধা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '430','district_id' => '57','name' => 'Palashbari','bn_name' => 'পলাশবাড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '431','district_id' => '57','name' => 'Saghata','bn_name' => 'সাঘাটা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '432','district_id' => '57','name' => 'Gobindaganj','bn_name' => 'গোবিন্দগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '433','district_id' => '57','name' => 'Sundarganj','bn_name' => 'সুন্দরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '434','district_id' => '57','name' => 'Phulchari','bn_name' => 'ফুলছড়ি','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '435','district_id' => '58','name' => 'Thakurgaon Sadar','bn_name' => 'ঠাকুরগাঁও সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '436','district_id' => '58','name' => 'Pirganj','bn_name' => 'পীরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '437','district_id' => '58','name' => 'Ranisankail','bn_name' => 'রাণীশংকৈল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '438','district_id' => '58','name' => 'Haripur','bn_name' => 'হরিপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '439','district_id' => '58','name' => 'Baliadangi','bn_name' => 'বালিয়াডাঙ্গী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '440','district_id' => '59','name' => 'Rangpur Sadar','bn_name' => 'রংপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '441','district_id' => '59','name' => 'Gangachara','bn_name' => 'গংগাচড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '442','district_id' => '59','name' => 'Taragonj','bn_name' => 'তারাগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '443','district_id' => '59','name' => 'Badargonj','bn_name' => 'বদরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '444','district_id' => '59','name' => 'Mithapukur','bn_name' => 'মিঠাপুকুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '445','district_id' => '59','name' => 'Pirgonj','bn_name' => 'পীরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '446','district_id' => '59','name' => 'Kaunia','bn_name' => 'কাউনিয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '447','district_id' => '59','name' => 'Pirgacha','bn_name' => 'পীরগাছা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '448','district_id' => '60','name' => 'Kurigram Sadar','bn_name' => 'কুড়িগ্রাম সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '449','district_id' => '60','name' => 'Nageshwari','bn_name' => 'নাগেশ্বরী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '450','district_id' => '60','name' => 'Bhurungamari','bn_name' => 'ভুরুঙ্গামারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '451','district_id' => '60','name' => 'Phulbari','bn_name' => 'ফুলবাড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '452','district_id' => '60','name' => 'Rajarhat','bn_name' => 'রাজারহাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '453','district_id' => '60','name' => 'Ulipur','bn_name' => 'উলিপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '454','district_id' => '60','name' => 'Chilmari','bn_name' => 'চিলমারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '455','district_id' => '60','name' => 'Rowmari','bn_name' => 'রৌমারী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '456','district_id' => '60','name' => 'Charrajibpur','bn_name' => 'চর রাজিবপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '457','district_id' => '61','name' => 'Sherpur Sadar','bn_name' => 'শেরপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '458','district_id' => '61','name' => 'Nalitabari','bn_name' => 'নালিতাবাড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '459','district_id' => '61','name' => 'Sreebordi','bn_name' => 'শ্রীবরদী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '460','district_id' => '61','name' => 'Nokla','bn_name' => 'নকলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '461','district_id' => '61','name' => 'Jhenaigati','bn_name' => 'ঝিনাইগাতী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '462','district_id' => '62','name' => 'Fulbaria','bn_name' => 'ফুলবাড়ীয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '463','district_id' => '62','name' => 'Trishal','bn_name' => 'ত্রিশাল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '464','district_id' => '62','name' => 'Bhaluka','bn_name' => 'ভালুকা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '465','district_id' => '62','name' => 'Muktagacha','bn_name' => 'মুক্তাগাছা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '466','district_id' => '62','name' => 'Mymensingh Sadar','bn_name' => 'ময়মনসিংহ সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '467','district_id' => '62','name' => 'Dhobaura','bn_name' => 'ধোবাউড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '468','district_id' => '62','name' => 'Phulpur','bn_name' => 'ফুলপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '469','district_id' => '62','name' => 'Haluaghat','bn_name' => 'হালুয়াঘাট','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '470','district_id' => '62','name' => 'Gouripur','bn_name' => 'গৌরীপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '471','district_id' => '62','name' => 'Gafargaon','bn_name' => 'গফরগাঁও','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '472','district_id' => '62','name' => 'Iswarganj','bn_name' => 'ঈশ্বরগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '473','district_id' => '62','name' => 'Nandail','bn_name' => 'নান্দাইল','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '474','district_id' => '62','name' => 'Tarakanda','bn_name' => 'তারাকান্দা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '475','district_id' => '63','name' => 'Jamalpur Sadar','bn_name' => 'জামালপুর সদর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '476','district_id' => '63','name' => 'Melandah','bn_name' => 'মেলান্দহ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '477','district_id' => '63','name' => 'Islampur','bn_name' => 'ইসলামপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '478','district_id' => '63','name' => 'Dewangonj','bn_name' => 'দেওয়ানগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '479','district_id' => '63','name' => 'Sarishabari','bn_name' => 'সরিষাবাড়ী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '480','district_id' => '63','name' => 'Madarganj','bn_name' => 'মাদারগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '481','district_id' => '63','name' => 'Bokshiganj','bn_name' => 'বকশীগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '482','district_id' => '64','name' => 'Barhatta','bn_name' => 'বারহাট্টা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '483','district_id' => '64','name' => 'Durgapur','bn_name' => 'দুর্গাপুর','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '484','district_id' => '64','name' => 'Kendua','bn_name' => 'কেন্দুয়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '485','district_id' => '64','name' => 'Atpara','bn_name' => 'আটপাড়া','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '486','district_id' => '64','name' => 'Madan','bn_name' => 'মদন','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '487','district_id' => '64','name' => 'Khaliajuri','bn_name' => 'খালিয়াজুরী','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '488','district_id' => '64','name' => 'Kalmakanda','bn_name' => 'কলমাকান্দা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '489','district_id' => '64','name' => 'Mohongonj','bn_name' => 'মোহনগঞ্জ','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '490','district_id' => '64','name' => 'Purbadhala','bn_name' => 'পূর্বধলা','created_at'=>$timestamp,'updated_at'=>$timestamp),
            array('id' => '491','district_id' => '64','name' => 'Netrokona Sadar','bn_name' => 'নেত্রকোণা সদর','created_at'=>$timestamp,'updated_at'=>$timestamp)
        );

        DB::table('upazilas')->insert($upazilas);
    }
}
